ruby '>= 2.5'
source 'https://rubygems.org'

# Middleman
gem 'middleman', :github => 'middleman/middleman', :branch => '4.x'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.5.0'
gem 'nokogiri', '~> 1.11.0'
gem 'sass'
gem 'webrick'
gem 'middleman-livereload' # NOTE: breaks if placed inside a group!
