const AssetType = {
	ORTHOPHOTO: "ORTHOPHOTO",
	TERRAIN_MODEL: "TERRAIN_MODEL",
	SURFACE_MODEL: "SURFACE_MODEL",
	POINTCLOUD: "POINTCLOUD",
	TEXTURED_MODEL: "TEXTURED_MODEL"
};

export default AssetType;
