const SourceType = {
	RASTER_IMAGERY: "RASTER_IMAGERY",
	RASTER_TERRAIN: "RASTER_TERRAIN",
	TERRAIN_DATABASE: "TERRAIN_DATABASE",
	CITYGML: "CITYGML",
	KML: "KML",
	CAPTURE: "3D_CAPTURE",
	MODEL: "3D_MODEL",
	POINTCLOUD: "POINT_CLOUD"
};

export default SourceType;
