# Chaining this file to the main docker-compose file setups
# volumes for NodeODX.

version: '2.1'
services:
  node-odx-1:
    volumes:
      - ${WO_NODE_DIR}/data:/var/www/data:Z
      - ${WO_NODE_DIR}/tmp:/var/www/tmp:Z