# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 14:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170615_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='orthophoto',
        ),
        migrations.AddField(
            model_name='task',
            name='orthophoto_extent',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Extent of the orthophoto created by OpenDroneMap', null=True, srid=4326),
        ),
    ]
