# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170721_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The person who owns this preset', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
