# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_uuids(apps, schema_editor):
    Task = apps.get_model('app', 'Task')
    for task in Task.objects.all():
        task.public_uuid = uuid.uuid4()
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171109_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=False, help_text='A flag indicating whether this task is available to the public'),
        ),
        migrations.AddField(
            model_name='task',
            name='public_uuid',
            field=models.UUIDField(db_index=True, null=True, help_text="Unique identifier used to retrieve a publicly shared task. This is better than ID because it's not sequential."),
        ),
        migrations.RunPython(create_uuids)
    ]
