# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_public_task_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False)
        )
    ]
