# Generated by Django 2.0.3 on 2018-03-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180219_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='processing_node',
            field=models.ForeignKey(blank=True, help_text='Processing node assigned to this task (or null if this task has not been associated yet)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeodm.ProcessingNode'),
        ),
    ]
