# Generated by Django 2.0.3 on 2018-04-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180311_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='processing_lock',
        ),
    ]
