# Generated by Django 2.1.7 on 2019-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_update_images_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('name', models.CharField(help_text='Plugin name', max_length=255, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this plugin is enabled.')),
            ],
        ),
    ]
