# Generated by Django 2.1.7 on 2019-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='partial',
            field=models.BooleanField(default=False, help_text='A flag indicating whether this task is currently waiting for information or files to be uploaded before being considered for processing.'),
        ),
    ]
