# Generated by Django 2.2.27 on 2023-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_task_epsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, db_index=True, default='', help_text='Project tags', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, db_index=True, default='', help_text='Task tags', verbose_name='Tags'),
        ),
    ]
