# Generated by Django 4.2.14 on 2024-08-20 05:00

import app.models.task
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_task_orthophoto_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugindatum',
            name='bool_value',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Bool value'),
        ),
        migrations.AlterField(
            model_name='plugindatum',
            name='json_value',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='JSON value'),
        ),
        migrations.AlterField(
            model_name='plugindatum',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='The user this setting belongs to. If NULL, the setting is global.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Options that define this preset (same format as in a Task's options).", validators=[app.models.task.validate_task_options], verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Options that are being used to process this task', validators=[app.models.task.validate_task_options], verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orthophoto_bands',
            field=models.JSONField(blank=True, default=list, help_text='List of orthophoto bands', verbose_name='Orthophoto Bands'),
        ),
        migrations.AlterField(
            model_name='task',
            name='potree_scene',
            field=models.JSONField(blank=True, default=dict, help_text='Serialized potree scene information used to save/load measurements and camera view angle', verbose_name='Potree Scene'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='border',
            field=colorfield.fields.ColorField(default='#e7e7e7', help_text='The color of most borders.', image_field=None, max_length=25, samples=None, verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_danger',
            field=colorfield.fields.ColorField(default='#e74c3c', help_text='Delete button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Danger'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_default',
            field=colorfield.fields.ColorField(default='#95a5a6', help_text='Default button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Default'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_primary',
            field=colorfield.fields.ColorField(default='#2c3e50', help_text='Primary button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dialog_warning',
            field=colorfield.fields.ColorField(default='#f39c12', help_text='The border color of warning dialogs.', image_field=None, max_length=25, samples=None, verbose_name='Dialog Warning'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='failed',
            field=colorfield.fields.ColorField(default='#ffcbcb', help_text='The background color of failed notifications.', image_field=None, max_length=25, samples=None, verbose_name='Failed'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_background',
            field=colorfield.fields.ColorField(default='#3498db', help_text="Background color of the site's header.", image_field=None, max_length=25, samples=None, verbose_name='Header Background'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_primary',
            field=colorfield.fields.ColorField(default='#ffffff', help_text="Text and icons in the site's header.", image_field=None, max_length=25, samples=None, verbose_name='Header Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='highlight',
            field=colorfield.fields.ColorField(default='#f7f7f7', help_text='The background color of panels and some borders.', image_field=None, max_length=25, samples=None, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=colorfield.fields.ColorField(default='#2c3e50', help_text='Most text, icons, and borders.', image_field=None, max_length=25, samples=None, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='The main background color, and text color of some buttons.', image_field=None, max_length=25, samples=None, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='success',
            field=colorfield.fields.ColorField(default='#cbffcd', help_text='The background color of success notifications.', image_field=None, max_length=25, samples=None, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tertiary',
            field=colorfield.fields.ColorField(default='#3498db', help_text='Navigation links.', image_field=None, max_length=25, samples=None, verbose_name='Tertiary'),
        ),
    ]
