# Generated by Django 2.2.27 on 2025-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20241106_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='slogan',
            field=models.CharField(blank=True, default='A user-friendly, commercial grade software for drone image processing.', help_text='A slogan for your application to show on the login page', max_length=255, null=True, verbose_name='Slogan'),
        ),
    ]
