# Generated by Django 2.2.27 on 2025-03-24 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20250321_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crop',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Polygon defining the crop area of this task', null=True, srid=4326, verbose_name='Crop Polygon'),
        ),
    ]
