# Generated by Django 2.2.27 on 2025-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20250219_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_logo_size',
            field=models.IntegerField(default=307, help_text='The size of the logo in pixels', verbose_name='App logo size'),
        ),
    ]
