# Generated by Django 2.2.27 on 2025-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_task_console_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cluster_id',
            field=models.IntegerField(blank=True, help_text='Cluster Id this user is assigned to', null=True, verbose_name='Cluster Id'),
        ),
    ]
