# Generated by Django 2.2.27 on 2025-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_task_console_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, db_index=True, default=None, help_text='Project Id', null=True, unique=True, verbose_name='Project Id')),
                ('project_public_id', models.UUIDField(blank=True, db_index=True, default=None, help_text='Public identifier of the project', null=True, unique=True, verbose_name='Public Id')),
                ('task_id', models.UUIDField(blank=True, db_index=True, default=None, help_text='Task Id', null=True, unique=True, verbose_name='Task Id')),
                ('cluster_id', models.IntegerField(help_text='Cluster Id to redirect to', verbose_name='Cluster Id')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
    ]
