# Generated by Django 2.2.27 on 2025-11-11 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0045_profile_cluster_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, db_index=True, default=None, help_text='Project Id', null=True, unique=True, verbose_name='Project Id')),
                ('project_public_id', models.UUIDField(blank=True, db_index=True, default=None, help_text='Public identifier of the project', null=True, unique=True, verbose_name='Public Id')),
                ('task_id', models.UUIDField(blank=True, db_index=True, default=None, help_text='Task Id', null=True, unique=True, verbose_name='Task Id')),
                ('owner', models.ForeignKey(help_text='The person associated with this redirect', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
    ]
