# Generated by Django 2.2.27 on 2025-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wkt',
            field=models.TextField(blank=True, default=None, help_text='WKT definition of the dataset (if georeferenced and EPSG code is not available)', null=True, verbose_name='WKT'),
        ),
    ]
