version: '3.8'

services:
  webodm:
    image: opendronemap/webodm_webapp:latest
    container_name: webodm-desktop
    ports:
      - "8000:8000"
    environment:
      - WO_PORT=8000
      - WO_HOST=localhost
      - WO_MEDIA_DIR=/webodm/app/media
      - WO_DB_DIR=/webodm/db
      - WO_DEFAULT_NODES=0
    volumes:
      - webodm_media:/webodm/app/media
      - webodm_db:/webodm/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nodeodm:
    image: opendronemap/nodeodm:latest
    container_name: nodeodm-desktop
    ports:
      - "3000:3000"
    environment:
      - NODEODM_PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  webodm_media:
    driver: local
  webodm_db:
    driver: local
