# Generated by Django 2.0.3 on 2018-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeodm', '0002_processingnode_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='token',
            field=models.CharField(blank=True, default='', help_text="Token to use for authentication. If the node doesn't have authentication, you can leave this field blank.", max_length=1024),
        ),
    ]
