# Generated by Django 2.0.3 on 2019-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeodm', '0004_processingnode_max_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingnode',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Optional label for this node. When set, this label will be shown instead of hostname:port.', max_length=255),
        ),
        migrations.AddField(
            model_name='processingnode',
            name='odm_version',
            field=models.CharField(help_text='ODM version used by the node.', max_length=32, null=True),
        ),
    ]
