# Generated by Django 2.1.7 on 2019-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeodm', '0006_auto_20190220_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingnode',
            name='odm_version',
        ),
        migrations.AddField(
            model_name='processingnode',
            name='engine',
            field=models.CharField(help_text='Engine used by the node.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processingnode',
            name='engine_version',
            field=models.CharField(help_text='Engine version used by the node.', max_length=32, null=True),
        ),
    ]
