# .github/workflows/deploy.yml
name: Deploy WebODM on Commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          cd /home/gennady/SFUODM
          git pull origin master
      - name: Stop WebODM
        run: |
          cd /home/gennady/SFUODM
          ./webodm.sh stop

      - name: Build WebODM images
        run: |
          cd /home/gennady/SFUODM
          ./webodm.sh rebuild

      - name: Start WebODM
        run: |
          cd /home/gennady/SFUODM
          ./webodm.sh start \
            --detached \
            --media-dir /odm-data/media \
            --db-dir /odm-data/db/

      - name: Prune unused Docker images and volumes
        run: |
          docker image prune -f
          docker volume prune -f
